#!/bin/sh 

# Projektdatei für fpdoc erstellen
#=================================

# Damit die Dokumentation immer vollständig ist, müssen die Quellcodedateien, die einbezogen werden sollen, als --input-Option angegeben werden. Dann muß dieses Skript ausgeführt werden, um eine Projektdatei für fpdoc zu erstellen

fpdoc --warn-no-node --input-dir=. --package=computer --content --descr-dir=docs --format=html --verbose --write-project=computer-html.dp --output=html

fpdoc --warn-no-node --input-dir=. --package=computer --content --descr-dir=docs --format=chm --verbose --write-project=computer-chm.dp --output=computer.chm

fpdoc --warn-no-node --input-dir=. --package=computer --content --descr-dir=docs --format=latex --verbose --write-project=computer-latex.dp --output=computer.tex
